# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nominet-epp}
  s.version = "0.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Geoff Garside"]
  s.date = %q{2011-05-04}
  s.description = %q{Client for communicating with the Nominet EPP}
  s.email = %q{geoff@geoffgarside.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "History.md",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/nominet-epp.rb",
    "lib/nominet-epp/helpers.rb",
    "lib/nominet-epp/operations.rb",
    "lib/nominet-epp/operations/check.rb",
    "lib/nominet-epp/operations/create.rb",
    "lib/nominet-epp/operations/delete.rb",
    "lib/nominet-epp/operations/fork.rb",
    "lib/nominet-epp/operations/hello.rb",
    "lib/nominet-epp/operations/info.rb",
    "lib/nominet-epp/operations/list.rb",
    "lib/nominet-epp/operations/lock.rb",
    "lib/nominet-epp/operations/merge.rb",
    "lib/nominet-epp/operations/poll.rb",
    "lib/nominet-epp/operations/renew.rb",
    "lib/nominet-epp/operations/transfer.rb",
    "lib/nominet-epp/operations/unlock.rb",
    "lib/nominet-epp/operations/unrenew.rb",
    "lib/nominet-epp/operations/update.rb",
    "nominet-epp.gemspec",
    "test/helper.rb",
    "test/test_nominet-epp.rb"
  ]
  s.homepage = %q{http://github.com/geoffgarside/nominet-epp}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Nominet EPP (Extensible Provisioning Protocol) Client}
  s.test_files = [
    "test/helper.rb",
    "test/test_nominet-epp.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<epp-client>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<epp-client>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<epp-client>, [">= 0"])
  end
end

