# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{nominet-epp}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Geoff Garside"]
  s.date = %q{2010-05-25}
  s.description = %q{Client for communicating with the Nominet EPP}
  s.email = %q{geoff@geoffgarside.co.uk}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/helpers.rb",
     "lib/nominet-epp.rb",
     "lib/operations.rb",
     "lib/operations/check.rb",
     "lib/operations/create.rb",
     "lib/operations/delete.rb",
     "lib/operations/fork.rb",
     "lib/operations/hello.rb",
     "lib/operations/info.rb",
     "lib/operations/list.rb",
     "lib/operations/lock.rb",
     "lib/operations/merge.rb",
     "lib/operations/poll.rb",
     "lib/operations/renew.rb",
     "lib/operations/transfer.rb",
     "lib/operations/unlock.rb",
     "lib/operations/unrenew.rb",
     "lib/operations/update.rb",
     "nominet-epp.gemspec",
     "test/helper.rb",
     "test/test_nominet-epp.rb"
  ]
  s.homepage = %q{http://github.com/geoffgarside/nominet-epp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Nominet EPP (Extensible Provisioning Protocol) Client}
  s.test_files = [
    "test/helper.rb",
     "test/test_nominet-epp.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_runtime_dependency(%q<epp-client>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<epp-client>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<epp-client>, [">= 0"])
  end
end

